<#import "blocks/template.ftlh" as t>
<@t.template user>
    <h1 style="text-align: center">Поиск товаров</h1><hr>
    <form method="get" action="/">
        <div class="form-row">
            <div class="form-group col-md-2">
                <label for="searchCity">Город</label>
                <select id="searchCity" name="city" class="form-control">
                    <option value="" <#if !searchCity?? || searchCity == "">selected</#if>>Город не выбран</option>
                    <option value="Москва" <#if searchCity?? && searchCity=="Москва">selected</#if>>Москва</option>
                    <option value="Красноярск" <#if searchCity?? && searchCity=="Красноярск">selected</#if>>Самара</option>
                    <option value="Казань" <#if searchCity?? && searchCity=="Казань">selected</#if>>Казань</option>
                </select>
            </div>
            <div class="form-group col-md-10">
                <label for="searchWord">Поиск по объявлениям</label>
                <input type="text" name="searchWord" <#if searchWord??>value="${searchWord}"</#if> class="form-control"
                       id="searchWord">
            </div>
            <button style="width: 100%" type="submit" class="btn btn-dark">Поиск</button>
        </div>
    </form>
    <hr>
    <div class="card-columns">
        <#list products.content as product>
            <a href="/product/${product.id}" class="product-link">
                <div class="card text-white bg-dark my-3 product">
                    <img src="/images/${product.previewImageId}"
                         class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">${product.title}</h5>
                        <p class="card-text">${product.price} ₽</p>
                    </div>
                    <div class="card-footer">
                        ${product.city}
                    </div>
                </div>
            </a>
        <#else>
            <h1 style="text-align: center">Не найдено</h1>
        </#list>
    </div>

    <nav aria-label="Page navigation" class="mt-4">
        <ul class="pagination justify-content-center">
            <li class="page-item <#if products.first>disabled</#if>">
                <a class="page-link" href="?page=${products.number-1}&searchWord=${searchWord!}&city=${searchCity!}">Previous</a>
            </li>
            <#list 0..products.totalPages-1 as i>
                <li class="page-item <#if i==products.number>active</#if>">
                    <a class="page-link" href="?page=${i}&searchWord=${searchWord!}&city=${searchCity!}">${i+1}</a>
                </li>
            </#list>
            <li class="page-item <#if products.last>disabled</#if>">
                <a class="page-link" href="?page=${products.number+1}&searchWord=${searchWord!}&city=${searchCity!}">Next</a>
            </li>
        </ul>
    </nav>
</@t.template>